my:
  greeting: Hello thiru update
  list: values:one,two,three
db:
  connection: This is test profile connection String
  server: 127.0.1
  port: 1000

management.endpoints.web.exposure.include: "*"
